# Generated by Django 3.2.7 on 2024-05-02 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0002_rename_password_internal_user_hashpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internal_user',
            name='Created_at',
        ),
        migrations.AddField(
            model_name='internal_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internal_user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
