# Generated by Django 3.2.7 on 2024-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0003_auto_20240503_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internal_user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='internal_user',
            name='Created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='internal_user',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
