# Generated by Django 3.2.7 on 2024-05-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0004_auto_20240503_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internal_user',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
