# Generated by Django 3.2.7 on 2024-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0005_rename_created_at_internal_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal_user',
            name='created_at',
            field=models.DateTimeField(default='2024-05-03T01:55:00Z'),
        ),
    ]
