# Generated by Django 3.2.7 on 2024-05-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0007_customtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='parent',
        ),
    ]
