# Generated by Django 3.2.7 on 2024-05-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0008_remove_permission_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_permission',
            name='parent',
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role_permission',
            name='permissionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADapp.permission'),
        ),
        migrations.AlterField(
            model_name='role_permission',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADapp.role'),
        ),
    ]
