# Generated by Django 3.2.7 on 2024-05-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0009_auto_20240504_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_meta',
            name='parent',
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADapp.u_user'),
        ),
    ]
