# Generated by Django 3.2.7 on 2024-05-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADapp', '0010_auto_20240504_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_owner_meta',
            name='Owner_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADapp.property_owner'),
        ),
    ]
